### ISSUE TITLE
No reviewes

### ISSUE THREAD

**Issue by cimice15** [philipperemy/amazon-reviews-scraper#12]
Since today no reviews are found when launching program.
Please fix.

**Comment by philipperemy** [comment]
@cimice15 hey did you solve your problem?

**Comment by cimice15** [comment]
Hi,
sometimes it works and sometimes not. I don’t know.
For example now if i try to search any object it returns 0 items. But until yesterday all worked well.

**Comment by philipperemy** [comment]
@cimice15 that's very weird. Do you make a lot of queries?

**Comment by cimice15** [comment]
No. But now it works... Too weird
