### ISSUE TITLE
VPS crash when I run the main program

### ISSUE THREAD

**Issue by ligua** [philipperemy/amazon-reviews-scraper#15]
Hi, Thank you for spending time reading this.

I am having a weird problem. I have an expressvpn subscription and I install the ubuntu python binding according to your post. The script runs on a remote server, a VPS in this case. Unfortunately,  the VPS usually freeze after I run the script and I have to restart the server. Any idea why that is the case or am I missing something?

Thank you so much and best regards

**Comment by philipperemy** [comment]
Can you try to run it locally and try to see if any errors occur (you need MacOS or Linux)? It's possible that we have to upgrade the express VPN to a newer version.

**Comment by philipperemy** [comment]
Try to run this script: https://github.com/philipperemy/expressvpn-python/blob/master/vpn.sh
It should update your IP every 60 seconds. I think that's a good start for troubleshooting.

**Comment by ligua** [comment]
Thank you so much for your quick response

Also, when I try to scrape with the keyword "umbrella", there is a section on the search result page that gives 

![image](https://user-images.githubusercontent.com/23098054/116196987-bcbdf300-a766-11eb-9e4b-c087ba0438ef.png)

which display on the webpage:

![image](https://user-images.githubusercontent.com/23098054/116197057-d19a8680-a766-11eb-9c9e-35e36337fa0c.png)

Is there a conflict between this section and the line 

![image](https://user-images.githubusercontent.com/23098054/116197247-158d8b80-a767-11eb-863d-ca036bf8172b.png)
