### ISSUE TITLE
Scrape the number of Helpful ratings

### ISSUE THREAD

**Issue by sughodke** [philipperemy/amazon-reviews-scraper#2]
Extending the scraper to include the number of times it was voted helpful by other Amazon users.

Add the below attribute to `get_comments_with_product_id()` and incorporate it in the reviews list.
```
helpful = review.find(attrs={'data-hook': 'helpful-vote-statement'}).text


# Retain only the number of helpful votes
helpful = helpful.strip().split(' ')[0]
```

**Comment by philipperemy** [comment]
@sughodke thanks! Can you open a Pull Request to reflect this change?

**Comment by philipperemy** [comment]
Done https://github.com/philipperemy/amazon-reviews-scraper/commit/3b70578c9d08632b52d7c4daa8dc408ad8c62490
