### ISSUE TITLE
Error while running amaon_comments_scraper.py

### ISSUE THREAD

**Issue by naman-gupta99** [philipperemy/amazon-reviews-scraper#8]
![image](https://user-images.githubusercontent.com/32611803/55014705-750d9000-5011-11e9-9a80-8c11a43322bf.png)

**Comment by philipperemy** [comment]
@naman-gupta99 thanks for reporting going to see that now

**Comment by philipperemy** [comment]
Amazon has changed their HTML so I'm going to update it.

**Comment by philipperemy** [comment]
update! Should be good

https://github.com/philipperemy/amazon-reviews-scraper/commit/f243bfcbc92e1767348924f98daf785c1409ab33
