### ISSUE TITLE
Can we get the URL for each review?

### ISSUE THREAD

**Issue by Blum** [philipperemy/amazon-reviews-scraper#9]
Hello, first - thank you very much for your work.

Is it possible in the output of amazon_comments_scraper.py also to have the URL of the review, not only the URL of the reviewer profile?

Like this one for example: https://www.amazon.com/gp/customer-reviews/RZIYA6PSUEN4Y/ref=cm_cr_arp_d_rvw_ttl?ie=UTF8&ASIN=B07C49KG8W

Thanks

**Comment by philipperemy** [comment]
@Blum thanks! yeah I think definitely possible. I won't have time to work on it in the short term. So maybe you can add this feature :)

**Comment by Blum** [comment]
Python is not very much of my powers, but I could try, Thank you :>

**Comment by Blum** [comment]
Here it is #10

**Comment by philipperemy** [comment]
@Blum awesome going to review that today ;)

**Comment by philipperemy** [comment]
https://github.com/philipperemy/amazon-reviews-scraper/commit/aebf7025d1d7ee0b4b9d2eeea65b4fb012284529 Thank you for your contribution!
